#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS AND COMMON FUNCTIONS
#=================================================
source /usr/share/yunohost/helpers
source _common.sh

#=================================================
# INSTALLATION SCRIPT
#=================================================

# Setup dir and env
ynh_print_info "Setting up directory..."
ynh_setup_source --dest_dir="$install_dir" --source_id="main"
ynh_setup_source --dest_dir="$install_dir/jdk" --source_id="jdk"
env_string="env PATH=$install_dir/jdk/bin:$PATH JAVA_HOME=$install_dir/jdk GRADLE_USER_HOME=$install_dir/.gradle"

ynh_print_info "Setting up variables..."
# Save user inputs from manifest into app settings
ynh_app_setting_set --app=$app --key=jellyfin_url --value="$jellyfin_url"
ynh_app_setting_set --app=$app --key=jellyfin_api_key --value="$jellyfin_api_key"
ynh_app_setting_set --app=$app --key=jellyfin_username --value="$jellyfin_username"
ynh_app_setting_set --app=$app --key=jellyfin_password --value="$jellyfin_password"
ynh_app_setting_set --app=$app --key=radarr_url --value="$radarr_url"
ynh_app_setting_set --app=$app --key=radarr_api_key --value="$radarr_api_key"
ynh_app_setting_set --app=$app --key=sonarr_url --value="$sonarr_url"
ynh_app_setting_set --app=$app --key=sonarr_api_key --value="$sonarr_api_key"
ynh_app_setting_set --app=$app --key=jellyseerr_url --value="$jellyseerr_url"
ynh_app_setting_set --app=$app --key=jellyseerr_api_key --value="$jellyseerr_api_key"
ynh_app_setting_set --app=$app --key=jellystat_url --value="$jellystat_url"
ynh_app_setting_set --app=$app --key=jellystat_api_key --value="$jellystat_api_key"
ynh_app_setting_set --app=$app --key=leaving_soon_dir --value="$leaving_soon_dir"
ynh_app_setting_set --app=$app --key=media_server_leaving_soon_dir --value="$media_server_leaving_soon_dir"
ynh_app_setting_set --app=$app --key=free_space_check_dir --value="$free_space_check_dir"
ynh_app_setting_set --app=$app --key=dry_run --value="$dry_run"
ynh_app_setting_set --app=$app --key=whole_tv_show --value="$whole_tv_show"
ynh_app_setting_set --app=$app --key=whole_show_seeding_check --value="$whole_show_seeding_check"
ynh_app_setting_set --app=$app --key=leaving_soon --value="$leaving_soon"
ynh_app_setting_set --app=$app --key=exclusion_tag --value="$exclusion_tag"
ynh_config_add --template="config" --destination="$install_dir/src/main/resources/application.yml"

# Add Janitorr to the multimedia group
ynh_print_info "Adding Janitorr to multimedia group..."
usermod -aG multimedia $app

# Create multimedia directories
ynh_print_info "Creating necessary directories..."
mkdir -p "/home/yunohost.multimedia/share/leavingsoon"

# Create application.yml using a template
ynh_print_info "Generating application.yml..."
cat > "$install_dir/src/main/resources/application.yml" <<EOL
server:
  port: $port

logging:
  level:
    com.github.schaka: INFO
  threshold:
    file: NONE # Set to TRACE to enable file logging

file-system:
  access: true
  validate-seeding: true
  leaving-soon-dir: "$leaving_soon_dir"
  media-server-leaving-soon-dir: "$media_server_leaving_soon_dir"
  from-scratch: true
  free-space-check-dir: "$free_space_check_dir"

application:
  dry-run: $dry_run
  run-once: false
  whole-tv-show: $whole_tv_show
  whole-show-seeding-check: $whole_show_seeding_check
  leaving-soon: $leaving_soon
  exclusion-tag: "$exclusion_tag"

  media-deletion:
    enabled: true
    movie-expiration:
      5: 15d 
      10: 30d 
      15: 30d 
      20: 90d 
    season-expiration:
      5: 15d 
      10: 20d 
      15: 60d 
      20: 120d 

  tag-based-deletion:
    enabled: false
    minimum-free-disk-percent: 100
    schedules:
      - tag: 5 - demo
        expiration: 30d
      - tag: 10 - demo
        expiration: 7d

  episode-deletion: # This ignores Jellystat. Only grab history matters. It also doesn't clean up Jellyfin. There is NO seeding check either.
    enabled: false
    tag: janitorr_daily # Shows tagged with this will have all episodes of their LATEST season deleted by the below thresholds
    max-episodes: 10 # maximum (latest) episodes of this season to keep
    max-age: 30d # Maximum age to keep any episode at all - even the last 10 episodes would expire after 30 days in this example

clients:
  jellyfin:
    enabled: true
    url: "$jellyfin_url"
    api-key: "$jellyfin_api_key"
    username: "$jellyfin_username"
    password: "$jellyfin_password"
    delete: true
    leaving-soon-tv: "Shows (Leaving Soon)"
    leaving-soon-movies: "Movies (Leaving Soon)"
  emby:
    enabled: false
    url: "http://localhost:8096"
    api-key: "4da8d93992804489ba2d1f0e31b8316c"
    username: Janitorr
    password: janitorr
    delete: true # Emby setup is required for JellyStat. However, if you don't want Janitorr to send delete requests to the Emby API, disable it here
    leaving-soon-tv: "Shows (Leaving Soon)"
    leaving-soon-movies: "Movies (Leaving Soon)"
  radarr:
    enabled: true
    url: "$radarr_url"
    api-key: "$radarr_api_key"
    only-delete-files: false
  sonarr:
    enabled: true
    url: "$sonarr_url"
    api-key: "$sonarr_api_key"
    delete-empty-shows: true
    determine-age-by: most_recent
  bazarr:
    enabled: false # Only used if you want to copy over subtitle files managed by Bazarr
    url: "http://localhost:6767"
    api-key: "cd0912f129d348c9b69bb20d49fcbe55"

  jellyseerr:
    enabled: true
    url: "$jellyseerr_url"
    api-key: "$jellyseerr_api_key"
    match-server: false
  jellystat:
    enabled: true
    url: "$jellystat_url"
    api-key: "$jellystat_api_key"
EOL

ynh_print_info "Downloading Janitorr JAR..."
wget -O "$install_dir/janitorr.jar" "https://github.com/botagas/janitorr_ynh/releases/download/latest/janitorr-master.jar"
chown -R "$app:$app" "$install_dir"

ynh_print_info "Adding systemd service..."
yunohost service add "$app" --description="Janitorr cleanup service"
ynh_config_add_systemd

ynh_print_info "Adding nginx configuration..."
ynh_config_add_nginx

ynh_print_info "Starting service..."
ynh_systemctl --service="$app" --action="start"

ynh_print_info "Installation completed!"
