#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

ynh_hide_warnings yunohost service remove "$app"
ynh_config_remove_systemd

ynh_config_remove_nginx

ynh_print_info "Removing app specific cron and etc data if present..."
ynh_safe_rm "/etc/cron.d/$app"
ynh_safe_rm "/etc/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
