#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================

ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace --source_id="main" --keep="application.yml"

# Initialize git repository and add Git history for the build system
pushd "$install_dir"
    git init
    git remote add origin https://github.com/Schaka/janitorr.git
    git fetch --depth 1 origin tag v1.7.2
    git checkout -f v1.7.2
popd

ynh_setup_source --dest_dir="$install_dir/jdk" --source_id="jdk"

env_string="env PATH=$install_dir/jdk/bin:$PATH JAVA_HOME=$install_dir/jdk GRADLE_USER_HOME=$install_dir/.gradle"

chown -R "$app:$app" "$install_dir"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================

ynh_print_info "Building Janitorr native executable..."

# Make gradlew executable
chmod +x "$install_dir/gradlew"

# Build the native executable using Gradle
pushd "$install_dir"
    ynh_exec_as_app $env_string ./gradlew nativeCompile
    ynh_exec_as_app cp "build/native/nativeCompile/janitorr" "janitorr"
    chmod +x "janitorr"
popd

chown -R "$app:$app" "$install_dir"

ynh_script_progression "Configuring nginx and systemd related to $app..."

# ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --description="Janitorr cleanup service"

# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate
touch /var/log/$app/$app.log

# Build YunoHost multimedia directories
ynh_multimedia_build_main_dir
# Enable writing into these directories
ynh_multimedia_addaccess $app

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
