name: Native Image

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build-native:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up GraalVM JDK 23
      uses: graalvm/setup-graalvm@v1
      with:
        java-version: '23'
        distribution: 'graalvm'
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Clone Janitorr Repository
      run: |
        git clone --depth 1 https://github.com/Schaka/janitorr.git
        cd janitorr
        sed -i 's|optional:file:/workspace/application.yml|optional:file:/var/www/janitorr/src/main/resources/application.yml|g' build.gradle.kts
        sed -i 's|optional:file:/workspace/application.yaml|optional:file:/var/www/janitorr/src/main/resources/application.yml|g' build.gradle.kts
        sed -i 's|optional:file:/config/application.yaml|optional:file:/var/www/janitorr/src/main/resources/application.yml|g' build.gradle.kts

    - name: Build Native Executable
      run: |
        cd janitorr
        ./gradlew nativeCompile

    - name: Rename Native Executable for Release
      run: |
        cd janitorr/build/native/nativeCompile
        if [[ "${GITHUB_REF##*/}" == "testing" || "${GITHUB_REF##*/}" == "testing-native" ]]; then
          mv janitorr janitorr-testing
        else
          mv janitorr janitorr-master
        fi

    - name: Set release binary name
      run: |
        if [[ "${GITHUB_REF##*/}" == "testing" || "${GITHUB_REF##*/}" == "testing-native" ]]; then
          echo "RELEASE_BIN_NAME=janitorr-testing" >> $GITHUB_ENV
        else
          echo "RELEASE_BIN_NAME=janitorr-master" >> $GITHUB_ENV
        fi

    - name: Upload Native Binary to GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        files: janitorr/build/native/nativeCompile/${{ env.RELEASE_BIN_NAME }}
        tag_name: ${{ github.ref_name }}
      env:
        USERNAME: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
