name: Native Image

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build-native:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        # cache: 'gradle'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Clone Janitorr Repository
      run: |
        git clone --depth 1 https://github.com/Schaka/janitorr.git
        cd janitorr
        sed -i 's|optional:file:/workspace/application.yml|optional:file:/var/www/janitorr/src/main/resources/application.yml|g' build.gradle.kts
        sed -i 's|optional:file:/workspace/application.yaml|optional:file:/var/www/janitorr/src/main/resources/application.yml|g' build.gradle.kts
        sed -i 's|optional:file:/config/application.yaml|optional:file:/var/www/janitorr/src/main/resources/application.yml|g' build.gradle.kts

    - name: Build Native Executable
      run: |
        cd janitorr
        ./gradlew nativeCompile

    - name: Upload Native Binary to GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        files: janitorr/build/native/nativeCompile/**
        tag_name: latest
      env:
        USERNAME: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
